name: realtime_taiwan
description: Realtime GIS browser for Taiwan.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+3

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_map: ^5.0.0
  html: ^0.15.4
  sqlite3: ^2.1.0
  path_provider: ^2.1.1
  url_launcher: ^6.1.14
  sqlite3_flutter_libs: ^0.5.16
  provider: ^6.0.5
  location: ^5.0.0
  flutter_localizations:
    sdk: flutter
  intl: any
  google_generative_ai: ^0.2.2
  dynamic_color: ^1.7.0
  mime: ^1.0.5
  gap: ^3.0.1
  cached_network_image: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons:
    git:
      url: https://github.com/fluttercommunity/flutter_launcher_icons.git
      ref: master

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/opendataCCTVs.xml

flutter_launcher_icons:
  android: true
  image_path: "assets/icons/ic_launcher.png"
  adaptive_icon_background: "assets/icons/background.png"
  adaptive_icon_foreground: "assets/icons/foreground.png"
  adaptive_icon_monochrome: "assets/icons/monochrome.png"
